// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnXX6HXUfPXJvW4lhzpnSz-t5zheMN0Wk',
    appId: '1:210673922111:web:7328f52b3a785e2de5c88a',
    messagingSenderId: '210673922111',
    projectId: 'bwtk-c2ebf',
    authDomain: 'bwtk-c2ebf.firebaseapp.com',
    storageBucket: 'bwtk-c2ebf.appspot.com',
    measurementId: 'G-HVB23F4HN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5oLUdn9LS-tjlFiLqitigbGk_8Jzj1ws',
    appId: '1:210673922111:android:797ac233f9a14770e5c88a',
    messagingSenderId: '210673922111',
    projectId: 'bwtk-c2ebf',
    storageBucket: 'bwtk-c2ebf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpmtnQbR25i16ioeuwWm78OLkMQLW3aIQ',
    appId: '1:210673922111:ios:e7c52ce51e685aeae5c88a',
    messagingSenderId: '210673922111',
    projectId: 'bwtk-c2ebf',
    storageBucket: 'bwtk-c2ebf.appspot.com',
    iosClientId: '210673922111-qjsl5fta2a5vrv1f4065qdtle5qs9dc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwtk',
  );
}
